export const typeColorMap: Record<string, string> = {
  Normal: "secondary",
  Fire: "danger",
  Water: "primary",
  Electric: "warning",
  Grass: "success",
  Ice: "info",
  Fighting: "danger",
  Poison: "purple",
  Ground: "brown",
  Flying: "indigo",
  Psychic: "pink",
  Bug: "success",
  Rock: "dark",
  Ghost: "dark",
  Dragon: "primary",
  Dark: "dark",
  Steel: "secondary",
  Fairy: "pink",
};
